In [3]:
import os
os.chdir("/kaggle/working")
!git clone https://github.com/hossamhamdy333/AI_Portfolio.git
os.chdir("/kaggle/working/AI_Portfolio")

fatal: destination path 'AI_Portfolio' already exists and is not an empty directory.

In [4]:
import getpass
GITHUB_USERNAME = "hossamhamdy333"
GITHUB_TOKEN = getpass.getpass("GitHub token: ")
REPO_NAME = "AI_Portfolio"
os.chdir("/kaggle/working/AI_Portfolio")
!git remote set-url origin https://{GITHUB_USERNAME}:{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git

GitHub token:  ········

In [5]:
PROJECT_FOLDER = "allam_finetune"
os.chdir(f"/kaggle/working/AI_Portfolio/{PROJECT_FOLDER}")
!pip install -r requirements.txt -q
!pip install "numpy<2" -q
!pip install -e . -q
print("All dependencies installed.")

  Preparing metadata (setup.py) ... done
All dependencies installed.

In [6]:
import random
import numpy as np
import torch
import pandas as pd
import yaml
import json
import logging

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
os.environ["USE_TF"] = "0"

!git pull origin main --rebase
with open("configs/config.yaml") as f:
    config = yaml.safe_load(f)

base = f"/kaggle/working/AI_Portfolio/{PROJECT_FOLDER}"

random.seed(config['data']['random_seed'])
np.random.seed(config['data']['random_seed'])
torch.manual_seed(config['data']['random_seed'])
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(config['data']['random_seed'])

logger = logging.getLogger(__name__)

From https://github.com/hossamhamdy333/AI_Portfolio
 * branch            main       -> FETCH_HEAD
Already up to date.

## Load Training Data

In [7]:
os.chdir(base)
train_df = pd.read_parquet(f"{base}/data/train.parquet")
train_df.head(2)

,instruction,input,output,system,task_type,source,instruction_count,input_count,output_count
0,استخرج الأحكام الأساسية من النص القانوني التالي:,لا يعفي من العقاب بالكلية من تعدي بنية سليمة ح...,تحليل المادة :\n\nالمجال القانوني: criminal_la...,أنت خبير قانوني في الشريعة والقانون المصري. اش...,analysis,curated_legal,7,52,61
1,اشرح هذا النص القانوني بلغة مبسطة للمواطن العادي:,كل من تسبب عمداً فى انقطاع المراسلات التلغرافي...,هذه المادة تتحدث عن كل من تسبب عمداً فى انقطاع...,أنت مساعد قانوني متخصص في القانون المصري. قدم ...,simplification,curated_legal,8,36,49

In [8]:
train_df.shape

(2392, 9)

In [9]:
train_df['task_type'].value_counts()

task_type
simplification         859
judgment_prediction    858
analysis               675
Name: count, dtype: int64

## Format Alpaca-Style Training Text

In [10]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(config['model']['base_model'])
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

def format_example(row):
    parts = []
    if row.get('system', ''):
        parts.append(row['system'])
    parts.append(f"### Instruction:\n{row['instruction']}")
    if row.get('input', ''):
        parts.append(f"### Input:\n{row['input']}")
    parts.append(f"### Response:\n{row['output']}")
    return "\n\n".join(parts) + tokenizer.eos_token

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

In [11]:
train_df['text'] = train_df.apply(format_example, axis=1)
print(train_df['text'].iloc[0])

أنت خبير قانوني في الشريعة والقانون المصري. اشرح الأحكام بوضوح.

### Instruction:
استخرج الأحكام الأساسية من النص القانوني التالي:

### Input:
لا يعفي من العقاب بالكلية من تعدي بنية سليمة حدود حق الدفاع الشرعي أثناء استعماله إياه دون أن يكون قاصداً إحداث ضرر أشد مما يستلزمه هذا الدفاع ،ومع ذلك يجوز للقاضي إذا كان الفعل جناية أن يعده معذورا إذا رأي لذلك محلا وأن يحكم عليه بالحبس بدلا من العقوبة المقررة فى القانون.

### Response:
تحليل المادة :

المجال القانوني: criminal_law
النقاط الرئيسية:
• لا يعفي من العقاب بالكلية من تعدي بنية سليمة حدود حق الدفاع الشرعي أثناء استعماله إياه دون أن يكون قاصداً إحداث ضرر أشد مما يستلزمه هذا الدفاع ،ومع ذلك يجوز للقاضي إذا كان الفعل جناية أن يعده معذورا إذا رأي لذلك محلا وأن يحكم عليه بالحبس بدلا من العقوبة المقررة فى القانون
</s>

In [12]:
from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df[['text']].reset_index(drop=True))
print(train_dataset)

Dataset({
    features: ['text'],
    num_rows: 2392
})

## Load Base Model in 4-bit

In [13]:
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

bnb_config = BitsAndBytesConfig(
    load_in_4bit=(config['qlora']['bits'] == 4),
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

In [14]:
tokenizer = AutoTokenizer.from_pretrained(config['model']['base_model'])
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [15]:
!pip install -q transformers==4.40.0 accelerate==0.29.3 bitsandbytes==0.43.1 torch==2.2.0

In [16]:
model = AutoModelForCausalLM.from_pretrained(
    config['model']['base_model'],
    quantization_config=bnb_config,
    device_map="auto",
)

config.json:   0%|          | 0.00/686 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading shards:   0%|          | 0/3 [00:00<?, ?it/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/4.03G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

## Apply LoRA Config

In [17]:
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=config['qlora']['r'],
    lora_alpha=config['qlora']['lora_alpha'],
    lora_dropout=config['qlora']['lora_dropout'],
    target_modules=config['qlora']['target_modules'],
    bias="none",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

trainable params: 79,953,920 || all params: 7,080,513,536 || trainable%: 1.1292107499475021

## Training Setup

In [18]:
from transformers import TrainingArguments
from trl import SFTTrainer

model.gradient_checkpointing_enable()
model.config.use_cache = False

checkpoint_dir = "/kaggle/working/qlora_checkpoints"  # session-local; see note on persisting across sessions

training_args = TrainingArguments(
    output_dir=checkpoint_dir,
    per_device_train_batch_size=config['training']['per_device_train_batch_size'],
    gradient_accumulation_steps=config['training']['gradient_accumulation_steps'],
    num_train_epochs=config['training']['num_train_epochs'],
    learning_rate=config['training']['learning_rate'],
    warmup_ratio=config['training']['warmup_ratio'],
    lr_scheduler_type=config['training']['lr_scheduler_type'],
    fp16=config['training']['fp16'],
    logging_steps=10,
    save_strategy="steps",
    save_steps=50,
    save_total_limit=3,
    report_to=[],
)

In [19]:
trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    dataset_text_field="text",
    max_seq_length=768,
    packing=False,
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Map:   0%|          | 0/2392 [00:00<?, ? examples/s]

## Resume-from-checkpoint check

In [20]:
import glob

existing_checkpoints = sorted(
    glob.glob(f"{checkpoint_dir}/checkpoint-*"),
    key=lambda p: int(p.split("-")[-1])
)
resume_path = existing_checkpoints[-1] if existing_checkpoints else None

if resume_path:
    print(f"Found existing checkpoint, will resume from: {resume_path}")
else:
    print("No existing checkpoint found,starting fresh from step 0.")

No existing checkpoint found,starting fresh from step 0.

## Train

In [21]:
train_result = trainer.train(resume_from_checkpoint=resume_path)

print("Training complete.")
print(f"Final train loss: {train_result.training_loss:.4f}")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Training complete.
Final train loss: 0.7230

## Save Adapter

In [27]:
import json, shutil

adapter_path = f"{base}/outputs/models/allam_qlora_adapter"
trainer.save_model(adapter_path)
tokenizer.save_pretrained(adapter_path)
print(f"Adapter saved to {adapter_path}")

with open(f"{adapter_path}/adapter_config.json") as f:
    saved_config = json.load(f)
print("Saved r:", saved_config["r"])
print("Saved lora_alpha:", saved_config["lora_alpha"])
print("Saved target_modules:", saved_config["target_modules"])

assert saved_config["r"] == config["qlora"]["r"], "Saved adapter r doesn't match config — do not proceed."
assert set(saved_config["target_modules"]) == set(config["qlora"]["target_modules"]), "target_modules mismatch — do not proceed."
print("Verified: r and target_modules match config.")

backup_path = "/kaggle/working/allam_qlora_adapter_backup"
shutil.rmtree(backup_path, ignore_errors=True)
shutil.copytree(adapter_path, backup_path)
print(f"Backup copy saved to {backup_path}")

Adapter saved to /kaggle/working/AI_Portfolio/allam_finetune/outputs/models/allam_qlora_adapter
Saved r: 32
Saved lora_alpha: 64
Saved target_modules: ['k_proj', 'v_proj', 'o_proj', 'up_proj', 'gate_proj', 'down_proj', 'q_proj']
Verified: r and target_modules match config.
Backup copy saved to /kaggle/working/allam_qlora_adapter_backup

## Push to Hugging Face Hub

In [26]:
!pip install -q huggingface_hub

from huggingface_hub import login
import getpass

HF_TOKEN = getpass.getpass("Hugging Face token: ")
login(token=HF_TOKEN)

model.push_to_hub("hossam3759180/allam-qlora-legal-adapter", token=HF_TOKEN)
tokenizer.push_to_hub("hossam3759180/allam-qlora-legal-adapter", token=HF_TOKEN)
print("Pushed to https://huggingface.co/hossam3759180/allam-qlora-legal-adapter")

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Hugging Face token:  ········

README.md: 0.00B [00:00, ?B/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

Pushed to https://huggingface.co/hossam3759180/allam-qlora-legal-adapter

## GitHub Push

In [58]:
import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"

In [62]:
import os
os.chdir("/kaggle/working/AI_Portfolio")

with open(".gitignore", "a") as f:
    f.write("\n*.safetensors\n*.bin\n*.pt\n")

!git add .gitignore
!git add -f allam_finetune/outputs/models/allam_qlora_adapter/adapter_config.json
!git add -f allam_finetune/outputs/models/allam_qlora_adapter/tokenizer_config.json
!git add -f allam_finetune/outputs/models/allam_qlora_adapter/tokenizer.json
!git add -f allam_finetune/outputs/models/allam_qlora_adapter/special_tokens_map.json

!git commit -m "add adapter configs"
!git push origin main

[main 8523989] add adapter configs
 1 file changed, 4 insertions(+)
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 4 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 313 bytes | 313.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/hossamhamdy333/AI_Portfolio.git
   2e8649a..8523989  main -> main