## Setup & Imports

In [5]:
import os
os.chdir("/kaggle/working")
!git clone https://github.com/hossamhamdy333/AI_Portfolio.git
os.chdir("/kaggle/working/AI_Portfolio")

fatal: destination path 'AI_Portfolio' already exists and is not an empty directory.

In [6]:
import getpass
GITHUB_USERNAME = "hossamhamdy333"
GITHUB_TOKEN = getpass.getpass("GitHub token: ")
REPO_NAME = "AI_Portfolio"
os.chdir("/kaggle/working/AI_Portfolio")
!git remote set-url origin https://{GITHUB_USERNAME}:{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git

GitHub token:  ········

In [7]:
PROJECT_FOLDER = "allam_finetune"
os.chdir(f"/kaggle/working/AI_Portfolio/{PROJECT_FOLDER}")
!pip install -r requirements.txt -q
!pip install "numpy<2" -q
!pip install -e . -q
print("All dependencies installed.")

  Preparing metadata (setup.py) ... done
All dependencies installed.

In [8]:
import random
import numpy as np
import torch
import pandas as pd
import yaml
import json
import logging

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
os.environ["USE_TF"] = "0"

!git pull origin main --rebase
with open("configs/config.yaml") as f:
    config = yaml.safe_load(f)

base = f"/kaggle/working/AI_Portfolio/{PROJECT_FOLDER}"

random.seed(config['data']['random_seed'])
np.random.seed(config['data']['random_seed'])
torch.manual_seed(config['data']['random_seed'])
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(config['data']['random_seed'])

logger = logging.getLogger(__name__)

From https://github.com/hossamhamdy333/AI_Portfolio
 * branch            main       -> FETCH_HEAD
Already up to date.

## Load Training Data

In [9]:
os.chdir(base)
train_df = pd.read_parquet(f"{base}/data/train.parquet")
train_df.head(2)

,instruction,input,output,system,task_type,source,instruction_count,input_count,output_count
424,اكتب نص الحكم النهائي الذي يتوافق مع الوقائع ا...,الوقائع:تتلخص وقائع هذه الدعوى في أنه سبق أن ت...,نص الحكم:فلكل ما تقدم، حكمت الدائرة: بإلزام ال...,,judgment_prediction,curated_ljp,10,328,46
454,اشرح هذا النص القانوني بلغة مبسطة للمواطن العادي:,كل عضو بمجلس إدارة إحدى الشركات المساهمة أو إح...,هذه المادة تتحدث عن كل عضو بمجلس إدارة إحدى ال...,أنت مساعد قانوني متخصص في القانون المصري. قدم ...,simplification,curated_legal,8,137,121

In [10]:
train_df.shape

(1942, 9)

In [11]:
train_df['task_type'].value_counts()

task_type
simplification         859
judgment_prediction    858
analysis               225
Name: count, dtype: int64

## Format Alpaca-Style Training Text

In [12]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(config['model']['base_model'])
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

def format_example(row):
    parts = []
    if row.get('system', ''):
        parts.append(row['system'])
    parts.append(f"### Instruction:\n{row['instruction']}")
    if row.get('input', ''):
        parts.append(f"### Input:\n{row['input']}")
    parts.append(f"### Response:\n{row['output']}")
    return "\n\n".join(parts) + tokenizer.eos_token

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [13]:
train_df['text'] = train_df.apply(format_example, axis=1)
print(train_df['text'].iloc[0])

### Instruction:
اكتب نص الحكم النهائي الذي يتوافق مع الوقائع الموضحة والأسباب.

### Input:
الوقائع:تتلخص وقائع هذه الدعوى في أنه سبق أن تقدم وكيل المدعية الموضح بياناته أعلاه بلائحة دعوى إلى المحكمة التجارية بالرياض ذكر فيها: انه سبق إقامة دعوى من المدعية ضد المدعى عليها المقيدة في المحكمة التجارية بالرياض برقم (٤٣٩١٧٣٩٥٢) وتاريخ ١٤٤٣/٠٨/١١هـ والمنظورة لدى (الرابعة عشر) بشأن المطالبة بـ(إنه بتاريخ ١٤٤١/٠٥/٠٦هـ الموافق ٢٠٢٠/٠١/٠١م اتفق أطراف الدعوى على أن تبيع المدعية للمدعى عليها حجر و جرانيت وتاريخ ابتداء التعامل ١٤٤١/٠٥/٠٦هـ الموافق ٢٠٢٠/٠١/٠١م بثمن إجمالي قدره (١,١٠٦,١١٤) مليون ومائة وستة ألفًا ومائة وأربعة عشر ريال لم تسدد منه شيء، وقد استلمت المدعى عليها كامل المبيع، وطالب بـ إلزام المدعى عليها بالتعويض بمبلغ قدره (٣٠,٠٠٠) ثلاثون ألفًا ريال، وقدم سنداً لطلبه المستندات الآتية: ١- صك حكم صادر من المحكمة التجارية بالرياض بتاريخ ١٤٤٤/٠٣/١٠هـ. ٢- عقد أتعاب محاماة. وقد عقدت الدائرة جلسة مرئية في ١٤٤٤/٠٧/٢٣هـ وملخصها: حضر وكيل المدعية، كما حضر وكيل المدعى عليها، وبسؤال وكيل المدعية عن الدعوى؟ أحال على ما ورد في صحيفة الدعوى، وبعرضها على وكيل المدعى عليها طلب مهلة فأفهمته الدائرة بأن تفاصيل هذه القضية ومبنى الادعاء فيها ظاهر وهي بلا تفاصيل وأسانيد وفواتير ونحوه، كما أنه سبق نظر الدعوى الأصلية فيها؛ وعليه فيلزمه الجواب في هذه الجلسة؛ فأجاب قائلا: لا أوافق على دعوى المدعية في أتعاب المحاماة، وأطلب رفضها، هكذا أجاب، وبعد دراسة القضية رأت الدائرة صلاحيتها للفصل فيها وأصدرت الدائرة حكمها مبنياً على ما يلي:
الأسباب:وبتأمل السابق، وقد حصر وكيل المدعية طلبه في: إلزام المدعى عليها بالتعويض بمبلغ قدره (٣٠,٠٠٠) ثلاثون ألفًا ريال، وحيث قدم وكيل المدعية في سبيل إثبات دعواه صك حكم، وعقد أتعاب محاماة، وبما أن من المقرر قضاءً ثبوت حق المدعية بالمطالبة بما تحملته من أتعاب نتيجة اللجوء للتقاضي، وقد نص شيخ الإسلام ابن تيمية- رحمه ﷲ -على: "أن صاحب الحق يحكم له بما غرمه من مال من أجل مطالبة خصمه وغريمه بحقه." وبما أن الدائرة ترى استحقاق المدعية لهذه المطالبة، ولما ألجأتها إليه المدعى عليها للتقاضي وتحملها تكاليف المرافعة والمدافعة، مما يتحقق معه الحال مع ما ذكر، ومما تقرر قضاءً من تحميل هذه الأمور على المتسبب، مما تنتهي معه الدائرة إلى قبول الطلب جزئياً.

### Response:
نص الحكم:فلكل ما تقدم، حكمت الدائرة: بإلزام المدعى عليها شركة الاريل للمقاولات والصناعة المحدودة، بالسجل التجاري رقم: (...) بأن تدفع للمدعية أريج بهجت شاكر المبيض، سجل مدني رقم: (...) مبلغا قدره (١١,٠٦١) أحد عشر ألفا وواحد وستون ريال، ورفضت الدعوى فيما زاد عن ذلك، وبالله التوفيق.</s>

In [14]:
from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df[['text']].reset_index(drop=True))
print(train_dataset)

Dataset({
    features: ['text'],
    num_rows: 1942
})

## Load Base Model in 4-bit

In [15]:
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

bnb_config = BitsAndBytesConfig(
    load_in_4bit=(config['qlora']['bits'] == 4),
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

In [16]:
tokenizer = AutoTokenizer.from_pretrained(config['model']['base_model'])
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [17]:
model = AutoModelForCausalLM.from_pretrained(
    config['model']['base_model'],
    quantization_config=bnb_config,
    device_map="auto",
)

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

## Apply LoRA Config

In [18]:
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=config['qlora']['r'],
    lora_alpha=config['qlora']['lora_alpha'],
    lora_dropout=config['qlora']['lora_dropout'],
    target_modules=config['qlora']['target_modules'],
    bias="none",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

trainable params: 8,388,608 || all params: 7,008,948,224 || trainable%: 0.11968426262981623

## Training Setup

In [19]:
from transformers import TrainingArguments
from trl import SFTTrainer

model.gradient_checkpointing_enable()
model.config.use_cache = False

checkpoint_dir = "/kaggle/working/qlora_checkpoints"  # session-local; see note on persisting across sessions

training_args = TrainingArguments(
    output_dir=checkpoint_dir,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=2,
    num_train_epochs=config['training']['num_train_epochs'],
    learning_rate=config['training']['learning_rate'],
    warmup_ratio=config['training']['warmup_ratio'],
    lr_scheduler_type=config['training']['lr_scheduler_type'],
    fp16=config['training']['fp16'],
    logging_steps=10,
    save_strategy="steps",
    save_steps=50,
    save_total_limit=3,
    report_to=[],
)

In [20]:
trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    dataset_text_field="text",
    max_seq_length=768,
    packing=False,
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Map:   0%|          | 0/1942 [00:00<?, ? examples/s]

## Resume-from-checkpoint check

In [21]:
import glob

existing_checkpoints = sorted(
    glob.glob(f"{checkpoint_dir}/checkpoint-*"),
    key=lambda p: int(p.split("-")[-1])
)
resume_path = existing_checkpoints[-1] if existing_checkpoints else None

if resume_path:
    print(f"Found existing checkpoint, will resume from: {resume_path}")
else:
    print("No existing checkpoint found,starting fresh from step 0.")

No existing checkpoint found,starting fresh from step 0.

In [22]:
os.chdir("/kaggle/working/AI_Portfolio/allam_finetune")
!sed -i 's/num_train_epochs: 3/num_train_epochs: 2/' configs/config.yaml
!sed -i 's/lora_dropout: 0.05/lora_dropout: 0.1/' configs/config.yaml
!grep -E "epoch|dropout" configs/config.yaml
!git add configs/config.yaml
!git commit -m "fix  config"
!git push origin main

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  lora_dropout: 0.1
  num_train_epochs: 2

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Everything up-to-date

## Train

In [23]:
import mlflow

mlflow.set_tracking_uri(config["mlflow"]["tracking_uri"])
mlflow.set_experiment(config["mlflow"]["experiment_name"])

with mlflow.start_run(run_name="qlora_finetune"):
    mlflow.log_param("base_model", config['model']['base_model'])
    mlflow.log_param("lora_r", config['qlora']['r'])
    mlflow.log_param("lora_alpha", config['qlora']['lora_alpha'])
    mlflow.log_param("target_modules", str(config['qlora']['target_modules']))
    mlflow.log_param("epochs", config['training']['num_train_epochs'])
    mlflow.log_param("learning_rate", config['training']['learning_rate'])
    mlflow.log_param("max_seq_length", 768)
    mlflow.log_param("train_rows", len(train_dataset))
    mlflow.log_param("resumed_from_checkpoint", resume_path is not None)

    train_result = trainer.train(resume_from_checkpoint=resume_path)

    mlflow.log_metric("final_train_loss", train_result.training_loss)
    for log in trainer.state.log_history:
        if "loss" in log:
            mlflow.log_metric("train_loss", log["loss"], step=log.get("step", 0))

print("Training complete.")
print(f"Final train loss: {train_result.training_loss:.4f}")

/usr/local/lib/python3.12/dist-packages/mlflow/utils/requirements_utils.py:20: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources  # noqa: TID251

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Training complete.
Final train loss: 0.9446

## Save Adapter

In [24]:
adapter_path = f"{base}/outputs/models/allam_qlora_adapter"
trainer.save_model(adapter_path)
tokenizer.save_pretrained(adapter_path)
print(f"Adapter saved to {adapter_path}")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Adapter saved to /kaggle/working/AI_Portfolio/allam_finetune/outputs/models/allam_qlora_adapter

## MLflow Model Registry

In [25]:
from mlflow.tracking import MlflowClient

client_mlf = MlflowClient()
run_id = mlflow.last_active_run().info.run_id if mlflow.last_active_run() else None

model_name = "allam_qlora"
try:
    client_mlf.create_registered_model(model_name)
except Exception:
    pass

mv = client_mlf.create_model_version(name=model_name, source=adapter_path, run_id=run_id)

## GitHub Push

In [26]:
os.chdir("/kaggle/working/AI_Portfolio")
!git add -f allam_finetune/outputs/models/allam_qlora_adapter
!git commit -m "add finetuned adapter"
!git push origin main

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

[main c969be3] add finetuned adapter
 2 files changed, 0 insertions(+), 0 deletions(-)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Enumerating objects: 15, done.
Counting objects: 100% (15/15), done.
Delta compression using up to 4 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 29.63 MiB | 11.93 MiB/s, done.
Total 8 (delta 5), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
To https://github.com/hossamhamdy333/AI_Portfolio.git
   62a86bb..c969be3  main -> main

In [28]:
os.chdir("/kaggle/working/AI_Portfolio")
!git config --global user.email "210591705+hossamhamdy333@users.noreply.github.com"
!git config --global user.name "Hossam Hamdy"
!git pull origin main --rebase

!git add .
!git commit -m "QLoRA training"
!git push origin main

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

From https://github.com/hossamhamdy333/AI_Portfolio
 * branch            main       -> FETCH_HEAD
Already up to date.

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Everything up-to-date