## Setup & Imports

In [1]:
from google.colab import drive
import os
drive.mount("/content/drive")
os.chdir("/content")
!git clone https://github.com/hossamhamdy333/AI_Portfolio.git
os.chdir("/content/AI_Portfolio")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
fatal: destination path 'AI_Portfolio' already exists and is not an empty directory.

In [2]:
import getpass
GITHUB_USERNAME = "hossamhamdy333"
GITHUB_TOKEN = getpass.getpass("GitHub token: ")
REPO_NAME = "AI_Portfolio"
os.chdir("/content/AI_Portfolio")
!git remote set-url origin https://{GITHUB_USERNAME}:{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git

GitHub token: ··········

In [3]:
PROJECT_FOLDER = "allam_finetune"
os.chdir(f"/content/AI_Portfolio/{PROJECT_FOLDER}")
!pip install -r requirements.txt -q
!pip install "numpy<2" -q
!pip install -e . -q
print("All dependencies installed.")

  Preparing metadata (setup.py) ... done
All dependencies installed.

In [4]:
import random
import numpy as np
import torch
import pandas as pd
import yaml
import json
import logging

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
os.environ["USE_TF"] = "0"

!git pull origin main --rebase
with open("configs/config.yaml") as f:
    config = yaml.safe_load(f)

base = f"/content/AI_Portfolio/{PROJECT_FOLDER}"

random.seed(config['data']['random_seed'])
np.random.seed(config['data']['random_seed'])
torch.manual_seed(config['data']['random_seed'])
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(config['data']['random_seed'])

logger = logging.getLogger(__name__)

From https://github.com/hossamhamdy333/AI_Portfolio
 * branch            main       -> FETCH_HEAD
Already up to date.

## Load Training Data

In [5]:
os.chdir(base)
!pip install "pathspec<0.12" -q
!dvc pull data/train.parquet.dvc data/val.parquet.dvc

Collecting          |2.00 [00:00, 55.5entry/s]
Fetching
!
  0% |          |0/? [00:00<?,    ?files/s]

!
  0% |          |0/? [00:00<?,    ?files/s]
 50% 1/2 [00:01<00:01,  1.40s/files{'info': ''}]
100% 2/2 [00:02<00:00,  1.16s/files{'info': ''}]

Fetching from local:   0% 0/2 [00:00<?, ?file/s]
Fetching from local:   0% 0/2 [00:00<?, ?file/s{'info': ''}]
Fetching
Building workspace index          |2.00 [00:00, 6.60entry/s]
Comparing indexes          |5.00 [00:00,  160entry/s]
Applying changes          |2.00 [00:00,  48.8file/s]
A       data/train.parquet
A       data/val.parquet
2 files added and 2 files fetched

In [6]:
train_df = pd.read_parquet(f"{base}/data/train.parquet")
train_df.head(2)

,instruction,input,output,system,task_type,source,instruction_count,input_count,output_count
3974,ولد نص الحكم النهائي باستخدام التحليل القانوني...,الوقائع:تتلخص وقائع هذه الدعوى في أنه تقدم إلى...,نص الحكم:بإلزام المدعى عليه بأن يدفع للمدعي مب...,,judgment_prediction,curated_ljp,9,376,40
3402,حدد نص الحكم بناء على الوقائع المعطاة.,الوقائع:تتلخص وقائع القضية الماثلة في أن وكيل ...,نص الحكم:حكمت الدائرة حضوريًا بإلزام محمد سعد ...,,judgment_prediction,curated_ljp,7,439,49

In [7]:
train_df.shape

(4332, 9)

In [8]:
train_df['task_type'].value_counts()

task_type
judgment_prediction    3249
simplification          858
analysis                225
Name: count, dtype: int64

## Format Alpaca-Style Training Text

In [9]:
def format_example(row):
    parts = []
    if row.get('system', ''):
        parts.append(row['system'])
    parts.append(f"### Instruction:\n{row['instruction']}")
    if row.get('input', ''):
        parts.append(f"### Input:\n{row['input']}")
    parts.append(f"### Response:\n{row['output']}")
    return "\n\n".join(parts)

In [10]:
train_df['text'] = train_df.apply(format_example, axis=1)
print(train_df['text'].iloc[0])

### Instruction:
ولد نص الحكم النهائي باستخدام التحليل القانوني للوقائع والأسباب.

### Input:
الوقائع:تتلخص وقائع هذه الدعوى في أنه تقدم إلى المحكمة وكيل المدعي بلائحة ادعاء يختصم فيها المدعى عليه قيدت القضية بالرقم المشار إليه أعلاه وأحيلت إلى هذه الدائرة وتـــم تــحــديــــــد مــــوعـــــــــــــد لــلــنــــظر فــيـــهـــا في جلسة يـــــوم ١٨/٩/١٤٤٣ تبين عدم حضور المدعى عليه رغم علمه بموعد هذه الجلسة ولم يودع المذكرة الدفاعية وأحال وكيل المدعي على لائحة الدعوى مضمونها (إنه بتاريخ ١٤٤١/٠٥/١١هـ الموافق ٢٠٢٠/٠١/٠٦م اتفق أطراف الدعوى على أن يؤجر المدعي للمدعى عليه الدراكتر لمدة (٣) ثلاثة أشهر ميلادية بواقع عشر ساعات عمل في اليوم الواحد بمبلغ وقدره { ١٣٤٦.١٥} الف وثلاثمائة وستة وأربعون ريال وخمسة عشر هللة ، بثمن إجمالي قدره (٦٣٨٢٥) ثلاثة وستون ألفًا وثمان مئة وخمسة وعشرون ريال، سدد منه {٦٠٠٠} ستة الاف ريال لسائق الدراكتر عبارة عن مرتب شهرين يناير ، وفبراير من عام ٢٠٢٠م علماً أن نشوء الحق كان بتاريخ ١٤٤١/٠٥/١١هـ الموافق ٢٠٢٠/٠١/٠٦م، ونشأ بسبب هذه العلاقة التجارية استلام المدعى عليه العين المؤجرة بتاريخ ١٤٤١/٠٥/١١هـ الموافق ٢٠٢٠/٠١/٠٦م، وانتهى العقد، ولم يسدد الأجرة المتبقية، وفترة المطالبة من تاريخ ١٤٤١/٠٥/١١هـ الموافق ٢٠٢٠/٠١/٠٦م حتى ١٤٤١/٠٨/٩هـ الموافق ٢٠٢٠/٠٤/٠٢م قد فشل المدعى عليه في سداد قيمة اجرة الدراكتر الحالة والمستحقة مبلغ وقدره (٦٣٨٢٥) ثلاثة وستون ألفًا وثمان مئة وخمسة وعشرون ريال ويطلب إلزامه بسداد هذا المبلغ) والبينة العقد على مطبوعات المدعى عليه وكشف الحساب، ثم رفعت الجلسة لإصدار الحكم مبيناً على الاتي من:
الأسباب:تأسيسا على ما تقدم، وبما أن قواعد الشريعة نصت على تحميل المدعية عبء تقديم البينة كما جاء عن ابن عباس رضي الله عنهما أن رسول الله صلى الله عليه وسلم قال :"لو يعطى الناس بدعواهم لادعى رجال أموال قوم ودماءهم، لكن البينة على المدعي واليمين على من أنكر" أخرجه البيهقي والترمذي والدارقطني وصححه الألباني، فأثبت الحديث باللفظ الصريح تحميل المدعي عبء إثبات دعواه من خلال تكليفه الإتيان بالبينة الملاقية لدعواه، وقد قال الإمام ابن القيم:" استقرت قاعدة الشريعة أن البينة على المدعي واليمين على المدعى عليه" (زاد المعاد ٥/٣٢٣)، وإذ قدم المدعي بينته على الدعوى من خلال العقد المبرم على مطبوعات المدعى عليه، وقوى صحة الدعوى عدم حضور المدعى عليه رغم تبلغه وعدم التزام المدعى عليه بإيداع المذكرة الدفاعية قبل يوم واحد عل الأقل قبل الجلسة بناء على الفقرة (٨١) من لائحة نظام المحاكم التجارية، ما تنتهي معه الدائرة إلى الحكم حضوريا بناء على الفقرة الأولى من المادة الثلاثون من نظام المحاكم التجارية بثبوت المبلغ الذي يطالب به المدعي في ذمة المدعى عليه وتلزمه بالسداد.

### Response:
نص الحكم:بإلزام المدعى عليه بأن يدفع للمدعي مبلغاً قدره ٦٣.٨٢٥ ثلاثة وستون ألفا وثمان مئة وخمسة وعشرون ريالا لما هو موضح في الأسباب. والله الموفق وصلى الله على نبينا محمد وعلى آله وسلم تسليما كثيرا.رئيس الدائرة القضائيةعمر بن حسين الحربي

In [11]:
from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df[['text']].reset_index(drop=True))
print(train_dataset)

Dataset({
    features: ['text'],
    num_rows: 4332
})

## Load Base Model in 4-bit

In [12]:
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

bnb_config = BitsAndBytesConfig(
    load_in_4bit=(config['qlora']['bits'] == 4),
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

In [13]:
tokenizer = AutoTokenizer.from_pretrained(config['model']['base_model'])
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

In [14]:
model = AutoModelForCausalLM.from_pretrained(
    config['model']['base_model'],
    quantization_config=bnb_config,
    device_map="auto",
)

config.json:   0%|          | 0.00/686 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading shards:   0%|          | 0/3 [00:00<?, ?it/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/4.03G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

## Apply LoRA Config

In [15]:
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=config['qlora']['r'],
    lora_alpha=config['qlora']['lora_alpha'],
    lora_dropout=config['qlora']['lora_dropout'],
    target_modules=config['qlora']['target_modules'],
    bias="none",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

trainable params: 8,388,608 || all params: 7,008,948,224 || trainable%: 0.11968426262981623

## Training Setup

In [16]:
from transformers import TrainingArguments
from trl import SFTTrainer

model.gradient_checkpointing_enable()
model.config.use_cache = False

checkpoint_dir = "/content/drive/MyDrive/AI_Portfolio_checkpoints/qlora_training"

training_args = TrainingArguments(
    output_dir=checkpoint_dir,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=2,
    num_train_epochs=config['training']['num_train_epochs'],
    learning_rate=config['training']['learning_rate'],
    warmup_ratio=config['training']['warmup_ratio'],
    lr_scheduler_type=config['training']['lr_scheduler_type'],
    fp16=config['training']['fp16'],
    logging_steps=10,
    save_strategy="steps",
    save_steps=50,
    save_total_limit=3,
    report_to=[],
)

In [17]:
trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    dataset_text_field="text",
    max_seq_length=768,
    packing=False,
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Map:   0%|          | 0/4332 [00:00<?, ? examples/s]

## Resume-from-checkpoint check

In [18]:
import glob

existing_checkpoints = sorted(
    glob.glob(f"{checkpoint_dir}/checkpoint-*"),
    key=lambda p: int(p.split("-")[-1])
)
resume_path = existing_checkpoints[-1] if existing_checkpoints else None

if resume_path:
    print(f"Found existing checkpoint, will resume from: {resume_path}")
else:
    print("No existing checkpoint found,starting fresh from step 0.")

Found existing checkpoint, will resume from: /content/drive/MyDrive/AI_Portfolio_checkpoints/qlora_training/checkpoint-1400

## Train

In [ ]:
import mlflow

mlflow.set_tracking_uri(config["mlflow"]["tracking_uri"])
mlflow.set_experiment(config["mlflow"]["experiment_name"])

with mlflow.start_run(run_name="qlora_finetune"):
    mlflow.log_param("base_model", config['model']['base_model'])
    mlflow.log_param("lora_r", config['qlora']['r'])
    mlflow.log_param("lora_alpha", config['qlora']['lora_alpha'])
    mlflow.log_param("target_modules", str(config['qlora']['target_modules']))
    mlflow.log_param("epochs", config['training']['num_train_epochs'])
    mlflow.log_param("learning_rate", config['training']['learning_rate'])
    mlflow.log_param("max_seq_length", 768)
    mlflow.log_param("train_rows", len(train_dataset))
    mlflow.log_param("resumed_from_checkpoint", resume_path is not None)

    train_result = trainer.train(resume_from_checkpoint=resume_path)

    mlflow.log_metric("final_train_loss", train_result.training_loss)
    for log in trainer.state.log_history:
        if "loss" in log:
            mlflow.log_metric("train_loss", log["loss"], step=log.get("step", 0))

print("Training complete.")
print(f"Final train loss: {train_result.training_loss:.4f}")

2026/07/29 01:13:58 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/07/29 01:13:58 INFO mlflow.store.db.utils: Updating database tables
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 451aebb31d03, add metric step
INFO  [alembic.runtime.migration] Running upgrade 451aebb31d03 -> 90e64c465722, migrate user column to tags
INFO  [alembic.runtime.migration] Running upgrade 90e64c465722 -> 181f10493468, allow nulls for metric values
INFO  [alembic.runtime.migration] Running upgrade 181f10493468 -> df50e92ffc5e, Add Experiment Tags Table
INFO  [alembic.runtime.migration] Running upgrade df50e92ffc5e -> 7ac759974ad8, Update run tags with larger limit
INFO  [alembic.runtime.migration] Running upgrade 7ac759974ad8 -> 89d4b8295536, create latest metrics table
INFO  [89d4b8295536_create_latest_metrics_table_py] Migration complete!
INFO  [alembic.runtime.migration] Running upgrade 89d4b8295536 -> 2b4d017a5e9b, add model registry tables to db
INFO  [2b4d017a5e9b_add_model_registry_tables_to_db_py] Adding registered_models and model_versions tables to database.
INFO  [2b4d017a5e9b_add_model_registry_tables_to_db_py] Migration complete!
INFO  [alembic.runtime.migration] Running upgrade 2b4d017a5e9b -> cfd24bdc0731, Update run status constraint with killed
INFO  [alembic.runtime.migration] Running upgrade cfd24bdc0731 -> 0a8213491aaa, drop_duplicate_killed_constraint
INFO  [alembic.runtime.migration] Running upgrade 0a8213491aaa -> 728d730b5ebd, add registered model tags table
INFO  [alembic.runtime.migration] Running upgrade 728d730b5ebd -> 27a6a02d2cf1, add model version tags table
INFO  [alembic.runtime.migration] Running upgrade 27a6a02d2cf1 -> 84291f40a231, add run_link to model_version
INFO  [alembic.runtime.migration] Running upgrade 84291f40a231 -> a8c4a736bde6, allow nulls for run_id
INFO  [alembic.runtime.migration] Running upgrade a8c4a736bde6 -> 39d1c3be5f05, add_is_nan_constraint_for_metrics_tables_if_necessary
INFO  [alembic.runtime.migration] Running upgrade 39d1c3be5f05 -> c48cb773bb87, reset_default_value_for_is_nan_in_metrics_table_for_mysql
INFO  [alembic.runtime.migration] Running upgrade c48cb773bb87 -> bd07f7e963c5, create index on run_uuid
INFO  [alembic.runtime.migration] Running upgrade bd07f7e963c5 -> 0c779009ac13, add deleted_time field to runs table
INFO  [alembic.runtime.migration] Running upgrade 0c779009ac13 -> cc1f77228345, change param value length to 500
INFO  [alembic.runtime.migration] Running upgrade cc1f77228345 -> 97727af70f4d, Add creation_time and last_update_time to experiments table
INFO  [alembic.runtime.migration] Running upgrade 97727af70f4d -> 3500859a5d39, Add Model Aliases table
INFO  [alembic.runtime.migration] Running upgrade 3500859a5d39 -> 7f2a7d5fae7d, add datasets inputs input_tags tables
INFO  [alembic.runtime.migration] Running upgrade 7f2a7d5fae7d -> 2d6e25af4d3e, increase max param val length from 500 to 8000
INFO  [alembic.runtime.migration] Running upgrade 2d6e25af4d3e -> acf3f17fdcc7, add storage location field to model versions
INFO  [alembic.runtime.migration] Running upgrade acf3f17fdcc7 -> 867495a8f9d4, add trace tables
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
2026/07/29 01:13:59 INFO mlflow.tracking.fluent: Experiment with name 'QLoRA_Fine_Tuning' does not exist. Creating a new experiment.

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

## Save Adapter

In [ ]:
adapter_path = f"{base}/outputs/models/allam_qlora_adapter"
trainer.save_model(adapter_path)
tokenizer.save_pretrained(adapter_path)
print(f"Adapter saved to {adapter_path}")

## DVC Push Adapter

In [ ]:
os.chdir(base)
!dvc add outputs/models/allam_qlora_adapter
!dvc push outputs/models/allam_qlora_adapter.dvc

## MLflow Model Registry

In [ ]:
from mlflow.tracking import MlflowClient

client_mlf = MlflowClient()
run_id = mlflow.last_active_run().info.run_id if mlflow.last_active_run() else None

model_name = "allam_qlora"
try:
    client_mlf.create_registered_model(model_name)
except Exception:
    pass

mv = client_mlf.create_model_version(name=model_name, source=adapter_path, run_id=run_id)

## GitHub Push

In [ ]:
import shutil
os.chdir("/content/AI_Portfolio")
!git config --global user.email "210591705+hossamhamdy333@users.noreply.github.com"
!git config --global user.name "Hossam Hamdy"
!git pull origin main --rebase
shutil.copy("/content/drive/MyDrive/Colab Notebooks/03_qlora_fine_tuning.ipynb", f"{base}/notebooks/03_qlora_fine_tuning.ipynb")

!git add .
!git commit -m "QLoRA training"
!git push origin main