## Setup & Imports

In [1]:
from google.colab import drive
import os
drive.mount("/content/drive")
os.chdir("/content")
!git clone https://github.com/hossamhamdy333/AI_Portfolio.git
os.chdir("/content/AI_Portfolio")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
fatal: destination path 'AI_Portfolio' already exists and is not an empty directory.

In [2]:
import getpass
GITHUB_USERNAME = "hossamhamdy333"
GITHUB_TOKEN = getpass.getpass("GitHub token: ")
REPO_NAME = "AI_Portfolio"
os.chdir("/content/AI_Portfolio")
!git remote set-url origin https://{GITHUB_USERNAME}:{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git

GitHub token: ··········

In [3]:
PROJECT_FOLDER = "allam_finetune"
os.chdir(f"/content/AI_Portfolio/{PROJECT_FOLDER}")

!pip install -q \
    transformers==4.40.0 \
    datasets==2.19.0 \
    torch==2.2.0 \
    peft==0.10.0 \
    trl==0.8.6 \
    bitsandbytes==0.43.1 \
    accelerate==0.29.3 \
    pandas==2.2.2 \
    "numpy<2" \
    PyYAML==6.0.1 \
    mlflow==2.13.0


print("ALL dependencies installed.")

ALL dependencies installed.

In [4]:
import random
import numpy as np
import torch
import pandas as pd
import yaml
import json
import logging
!git pull origin main --rebase

with open("configs/config.yaml") as f:
    config = yaml.safe_load(f)

base = f"/content/AI_Portfolio/{PROJECT_FOLDER}"

random.seed(config['data']['random_seed'])
np.random.seed(config['data']['random_seed'])

logger = logging.getLogger(__name__)

error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

## Load Training Data

In [5]:
os.chdir(base)
!pip install "pathspec<0.12" dvc==3.49.0 dvc-gdrive==3.0.1 -q
!dvc pull data/train.parquet.dvc data/val.parquet.dvc

Collecting          |0.00 [00:00,    ?entry/s]
Fetching
!
  0% |          |0/? [00:00<?,    ?files/s]
Fetching
Building workspace index          |4.00 [00:00,  565entry/s]
Comparing indexes          |5.00 [00:00,  892entry/s]
Applying changes          |0.00 [00:00,     ?file/s]
Everything is up to date.

In [6]:
train_df = pd.read_parquet(f"{base}/data/train.parquet")
train_df.head(2)

,instruction,input,output,system,task_type,source,instruction_count,input_count,output_count
3974,ولد نص الحكم النهائي باستخدام التحليل القانوني...,الوقائع:تتلخص وقائع هذه الدعوى في أنه تقدم إلى...,نص الحكم:بإلزام المدعى عليه بأن يدفع للمدعي مب...,,judgment_prediction,curated_ljp,9,376,40
3402,حدد نص الحكم بناء على الوقائع المعطاة.,الوقائع:تتلخص وقائع القضية الماثلة في أن وكيل ...,نص الحكم:حكمت الدائرة حضوريًا بإلزام محمد سعد ...,,judgment_prediction,curated_ljp,7,439,49

In [7]:
train_df.shape

(4332, 9)

## Alpaca-Style Training Text

In [8]:
def alpaca(row):
    parts = []
    if row.get('system', ''):
        parts.append(row['system'])
    parts.append(f"### Instruction:\n{row['instruction']}")
    if row.get('input', ''):
        parts.append(f"### Input:\n{row['input']}")
    parts.append(f"### Response:\n{row['output']}")
    return "\n\n".join(parts)

In [9]:
train_df['text'] = train_df.apply(alpaca, axis=1)
train_df['text'].iloc[0]

'### Instruction:\nولد نص الحكم النهائي باستخدام التحليل القانوني للوقائع والأسباب.\n\n### Input:\nالوقائع:تتلخص وقائع هذه الدعوى في أنه تقدم إلى المحكمة وكيل المدعي بلائحة ادعاء يختصم فيها المدعى عليه قيدت القضية بالرقم المشار إليه أعلاه وأحيلت إلى هذه الدائرة وتـــم تــحــديــــــد مــــوعـــــــــــــد لــلــنــــظر فــيـــهـــا في جلسة يـــــوم ١٨/٩/١٤٤٣ تبين عدم حضور المدعى عليه رغم علمه بموعد هذه الجلسة ولم يودع المذكرة الدفاعية وأحال وكيل المدعي على لائحة الدعوى مضمونها (إنه بتاريخ ١٤٤١/٠٥/١١هـ الموافق ٢٠٢٠/٠١/٠٦م اتفق أطراف الدعوى على أن يؤجر المدعي للمدعى عليه الدراكتر لمدة (٣) ثلاثة أشهر ميلادية بواقع عشر ساعات عمل في اليوم الواحد بمبلغ وقدره { ١٣٤٦.١٥} الف وثلاثمائة وستة وأربعون ريال وخمسة عشر هللة ، بثمن إجمالي قدره (٦٣٨٢٥) ثلاثة وستون ألفًا وثمان مئة وخمسة وعشرون ريال، سدد منه {٦٠٠٠} ستة الاف ريال لسائق الدراكتر عبارة عن مرتب شهرين يناير ، وفبراير من عام ٢٠٢٠م علماً أن نشوء الحق كان بتاريخ ١٤٤١/٠٥/١١هـ الموافق ٢٠٢٠/٠١/٠٦م، ونشأ بسبب هذه العلاقة التجارية استلام المدعى عليه العين المؤجرة بتاريخ ١٤٤١/٠٥/١١هـ الموافق ٢٠٢٠/٠١/٠٦م، وانتهى العقد، ولم يسدد الأجرة المتبقية، وفترة المطالبة من تاريخ ١٤٤١/٠٥/١١هـ الموافق ٢٠٢٠/٠١/٠٦م حتى ١٤٤١/٠٨/٩هـ الموافق ٢٠٢٠/٠٤/٠٢م قد فشل المدعى عليه في سداد قيمة اجرة الدراكتر الحالة والمستحقة مبلغ وقدره (٦٣٨٢٥) ثلاثة وستون ألفًا وثمان مئة وخمسة وعشرون ريال ويطلب إلزامه بسداد هذا المبلغ) والبينة العقد على مطبوعات المدعى عليه وكشف الحساب، ثم رفعت الجلسة لإصدار الحكم مبيناً على الاتي من:\nالأسباب:تأسيسا على ما تقدم، وبما أن قواعد الشريعة نصت على تحميل المدعية عبء تقديم البينة كما جاء عن ابن عباس رضي الله عنهما أن رسول الله صلى الله عليه وسلم قال :"لو يعطى الناس بدعواهم لادعى رجال أموال قوم ودماءهم، لكن البينة على المدعي واليمين على من أنكر" أخرجه البيهقي والترمذي والدارقطني وصححه الألباني، فأثبت الحديث باللفظ الصريح تحميل المدعي عبء إثبات دعواه من خلال تكليفه الإتيان بالبينة الملاقية لدعواه، وقد قال الإمام ابن القيم:" استقرت قاعدة الشريعة أن البينة على المدعي واليمين على المدعى عليه" (زاد المعاد ٥/٣٢٣)، وإذ قدم المدعي بينته على الدعوى من خلال العقد المبرم على مطبوعات المدعى عليه، وقوى صحة الدعوى عدم حضور المدعى عليه رغم تبلغه وعدم التزام المدعى عليه بإيداع المذكرة الدفاعية قبل يوم واحد عل الأقل قبل الجلسة بناء على الفقرة (٨١) من لائحة نظام المحاكم التجارية، ما تنتهي معه الدائرة إلى الحكم حضوريا بناء على الفقرة الأولى من المادة الثلاثون من نظام المحاكم التجارية بثبوت المبلغ الذي يطالب به المدعي في ذمة المدعى عليه وتلزمه بالسداد.\n\n### Response:\nنص الحكم:بإلزام المدعى عليه بأن يدفع للمدعي مبلغاً قدره ٦٣.٨٢٥ ثلاثة وستون ألفا وثمان مئة وخمسة وعشرون ريالا لما هو موضح في الأسباب. والله الموفق وصلى الله على نبينا محمد وعلى آله وسلم تسليما كثيرا.رئيس الدائرة القضائيةعمر بن حسين الحربي'

In [10]:
from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df[['text']].reset_index(drop=True))
train_dataset

Dataset({
    features: ['text'],
    num_rows: 4332
})

## Load Base Model in 4-bit

In [11]:
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

bnb_config = BitsAndBytesConfig(
    load_in_4bit=(config['qlora']['bits'] == 4),
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

In [12]:
tokenizer = AutoTokenizer.from_pretrained(config['model']['base_model'])
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [13]:
model = AutoModelForCausalLM.from_pretrained(
    config['model']['base_model'],
    quantization_config=bnb_config,
    device_map="auto",
)

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

## Apply LoRA Config

In [14]:
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=config['qlora']['r'],
    lora_alpha=config['qlora']['lora_alpha'],
    lora_dropout=config['qlora']['lora_dropout'],
    target_modules=config['qlora']['target_modules'],
    bias="none",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

trainable params: 8,388,608 || all params: 7,008,948,224 || trainable%: 0.11968426262981623

In [15]:
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

## Training Setup

In [20]:
from transformers import TrainingArguments
from trl import SFTTrainer

model.gradient_checkpointing_enable()
model.config.use_cache = False

training_args = TrainingArguments(
    output_dir=f"{base}/outputs/models/checkpoints",
    per_device_train_batch_size=4,
    gradient_accumulation_steps=2,
    num_train_epochs=3,
    learning_rate=config['training']['learning_rate'],
    warmup_ratio=config['training']['warmup_ratio'],
    lr_scheduler_type=config['training']['lr_scheduler_type'],
    fp16=config['training']['fp16'],
    logging_steps=5,
    save_strategy="steps",
    save_steps=25,
    report_to=[],
)

In [21]:
trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    dataset_text_field="text",
    max_seq_length=512,
    packing=False,
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Map:   0%|          | 0/4332 [00:00<?, ? examples/s]

In [25]:
import time
from transformers import TrainerCallback

class TimeLimitCallback(TrainerCallback):
    def __init__(self, max_minutes):
        self.max_seconds = max_minutes * 60
        self.start_time = None

    def on_train_begin(self, args, state, control, **kwargs):
        self.start_time = time.time()

    def on_step_end(self, args, state, control, **kwargs):
        if time.time() - self.start_time > self.max_seconds:
            print(f"\nTime limit reached ({self.max_seconds/60:.0f} min) — stopping training, saving checkpoint.")
            control.should_training_stop = True
        return control

trainer.add_callback(TimeLimitCallback(max_minutes=35))

## Train

In [26]:
import mlflow

mlflow.set_tracking_uri(config["mlflow"]["tracking_uri"])
mlflow.set_experiment(config["mlflow"]["experiment_name"])

with mlflow.start_run(run_name="qlora_finetune_v1"):
    mlflow.log_param("base_model", config['model']['base_model'])
    mlflow.log_param("lora_r", config['qlora']['r'])
    mlflow.log_param("lora_alpha", config['qlora']['lora_alpha'])
    mlflow.log_param("target_modules", str(config['qlora']['target_modules']))
    mlflow.log_param("epochs", config['training']['num_train_epochs'])
    mlflow.log_param("learning_rate", config['training']['learning_rate'])
    mlflow.log_param("train_rows", len(train_dataset))

    train_result = trainer.train()

    mlflow.log_metric("final_train_loss", train_result.training_loss)
    for log in trainer.state.log_history:
        if "loss" in log:
            mlflow.log_metric("train_loss", log["loss"], step=log.get("step", 0))

print("Training complete.")
print(f"Final train loss: {train_result.training_loss:.4f}")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Time limit reached (35 min) — stopping training, saving checkpoint.
Training complete.
Final train loss: 1.2680

## Save Adapter

In [27]:
adapter_path = f"{base}/outputs/models/allam_qlora_adapter"
trainer.save_model(adapter_path)
tokenizer.save_pretrained(adapter_path)
print(f"Adapter saved to {adapter_path}")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Adapter saved to /content/AI_Portfolio/allam_finetune/outputs/models/allam_qlora_adapter

## DVC Push

In [28]:
os.chdir(base)
!dvc add outputs/models/allam_qlora_adapter
!dvc push outputs/models/allam_qlora_adapter.dvc

⠋ Checking graph
Adding...:   0% 0/1 [00:00<?, ?file/s{'info': ''}]
!
          |0.00 [00:00,     ?file/s]

!
  0% |          |0/? [00:00<?,    ?files/s]

Adding outputs/models/allam_qlora_adapter to cache:   0% 0/8 [00:00<?, ?file/s]
  0% 0/8 [00:00<?, ?file/s{'info': ''}]

  0% 0/9 [00:00<?, ?files/s]
  0% 0/9 [00:00<?, ?files/s{'info': ''}]
Adding...: 100% 1/1 [00:00<00:00,  5.48file/s{'info': ''}]

To track the changes with git, run:

	git add outputs/models/.gitignore outputs/models/allam_qlora_adapter.dvc

To enable auto staging, run:

	dvc config core.autostage true
Collecting          |9.00 [00:00,  155entry/s]
Pushing
Querying remote cache:   0% 0/1 [00:00<?, ?files/s]
Querying remote cache:   0% 0/1 [00:00<?, ?files/s{'info': ''}]

!
  0% |          |0/? [00:00<?,    ?files/s]

!
  0% |          |0/? [00:00<?,    ?files/s]

Pushing to local:   0% 0/9 [00:00<?, ?file/s]
Pushing to local:   0% 0/9 [00:00<?, ?file/s{'info': ''}]
Pushing to local:  25% 2/8 [00:00<00:00, 17.47file/s{'info': ''}]
Pushing to local:  50% 4/8 [00:00<00:00,  6.82file/s{'info': ''}]
  0%|          |Pushing to local                  9/? [00:00<00:00, 15.84file/s]
Pushing
9 files pushed

## MLflow Model Registry

In [29]:
from mlflow.tracking import MlflowClient

client_mlf = MlflowClient()
run_id = mlflow.last_active_run().info.run_id if mlflow.last_active_run() else None

model_name = "allam_qlora"
try:
    client_mlf.create_registered_model(model_name)
except Exception:
    pass

mv = client_mlf.create_model_version(name=model_name, source=adapter_path, run_id=run_id)
client_mlf.set_registered_model_alias(model_name, "staging", mv.version)
print(f"Registered {model_name} v{mv.version} as staging")

Registered allam_qlora v1 as staging

## GitHub Push

In [30]:
import shutil
os.chdir("/content/AI_Portfolio")
!git config --global user.email "210591705+hossamhamdy333@users.noreply.github.com"
!git config --global user.name "Hossam Hamdy"
!git pull origin main --rebase
shutil.copy("/content/drive/MyDrive/Colab Notebooks/03_qlora_fine_tuning.ipynb", f"{base}/notebooks/03_qlora_fine_tuning.ipynb")
!git add .
!git add -f outputs/models/allam_qlora_adapter.dvc
!git commit -m "QLoRA training"
!git push origin main

error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
fatal: pathspec 'outputs/models/allam_qlora_adapter.dvc' did not match any files
[main 937555e] QLoRA training
 65 files changed, 999443 insertions(+), 1 deletion(-)
 rewrite allam_finetune/mlflow.db (76%)
 rewrite allam_finetune/notebooks/03_qlora_fine_tuning.ipynb (92%)
 create mode 100644 allam_finetune/outputs/models/.gitignore
 create mode 100644 allam_finetune/outputs/models/allam_qlora_adapter.dvc
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-100/README.md
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-100/adapter_config.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-100/adapter_model.safetensors
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-100/optimizer.pt
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-100/rng_state.pth
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-100/scheduler.pt
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-100/special_tokens_map.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-100/tokenizer.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-100/tokenizer.model
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-100/tokenizer_config.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-100/trainer_state.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-100/training_args.bin
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-125/README.md
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-125/adapter_config.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-125/adapter_model.safetensors
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-125/optimizer.pt
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-125/rng_state.pth
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-125/scheduler.pt
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-125/special_tokens_map.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-125/tokenizer.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-125/tokenizer.model
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-125/tokenizer_config.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-125/trainer_state.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-125/training_args.bin
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-25/README.md
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-25/adapter_config.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-25/adapter_model.safetensors
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-25/optimizer.pt
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-25/rng_state.pth
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-25/scheduler.pt
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-25/special_tokens_map.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-25/tokenizer.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-25/tokenizer.model
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-25/tokenizer_config.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-25/trainer_state.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-25/training_args.bin
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-50/README.md
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-50/adapter_config.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-50/adapter_model.safetensors
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-50/optimizer.pt
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-50/rng_state.pth
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-50/scheduler.pt
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-50/special_tokens_map.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-50/tokenizer.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-50/tokenizer.model
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-50/tokenizer_config.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-50/trainer_state.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-50/training_args.bin
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-75/README.md
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-75/adapter_config.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-75/adapter_model.safetensors
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-75/optimizer.pt
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-75/rng_state.pth
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-75/scheduler.pt
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-75/special_tokens_map.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-75/tokenizer.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-75/tokenizer.model
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-75/tokenizer_config.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-75/trainer_state.json
 create mode 100644 allam_finetune/outputs/models/checkpoints/checkpoint-75/training_args.bin
Enumerating objects: 57, done.
Counting objects: 100% (57/57), done.
Delta compression using up to 2 threads
Compressing objects: 100% (48/48), done.
Writing objects: 100% (49/49), 442.38 MiB | 9.44 MiB/s, done.
Total 49 (delta 22), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (22/22), completed with 7 local objects.
remote: warning: See https://gh.io/lfs for more information.
remote: warning: File allam_finetune/outputs/models/checkpoints/checkpoint-75/optimizer.pt is 64.10 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File allam_finetune/outputs/models/checkpoints/checkpoint-100/optimizer.pt is 64.10 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File allam_finetune/outputs/models/checkpoints/checkpoint-125/optimizer.pt is 64.10 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File allam_finetune/outputs/models/checkpoints/checkpoint-25/optimizer.pt is 64.10 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File allam_finetune/outputs/models/checkpoints/checkpoint-50/optimizer.pt is 64.10 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To https://github.com/hossamhamdy333/AI_Portfolio.git
   4436e0d..937555e  main -> main

In [32]:
gitignore_path = f"{base}/outputs/models/.gitignore"
with open(gitignore_path, "a") as f:
    f.write("\ncheckpoints/\n")
os.chdir("/content/AI_Portfolio")
!git rm -r --cached allam_finetune/outputs/models/checkpoints
!git add allam_finetune/outputs/models/.gitignore
!git commit -m "QLoRA training"
!git push origin main

fatal: pathspec 'allam_finetune/outputs/models/checkpoints' did not match any files
[main b2ed63f] QLoRA training
 1 file changed, 2 insertions(+)
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 2 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 575 bytes | 575.00 KiB/s, done.
Total 6 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/hossamhamdy333/AI_Portfolio.git
   1d05778..b2ed63f  main -> main